In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model, datasets, tree
import matplotlib.pyplot as plt
%matplotlib inline
import math as m

In [2]:
dataframe = pd.read_csv("iris.csv",header=None) #load the dataset
df = dataframe.values
dataset = df[:,0:4]
target = df[:,4]

In [3]:
for i in range(4):
    print(np.mean(dataset[:,i]), np.max(dataset[:,i]), np.min(dataset[:,i]))

5.843333333333335 7.9 4.3
3.0540000000000007 4.4 2.0
3.7586666666666693 6.9 1.0
1.1986666666666672 2.5 0.1


In [4]:
meu = list(np.mean(dataset[:,i]) for i in range(np.shape(dataset)[1]))

In [5]:
def pearson_coef(X,Y,mx,my):
    A = sum((X-mx)*(Y-my))
    B = m.sqrt(sum([a*b for a,b in zip(X-mx,X-mx)]))
    C = m.sqrt(sum([a*b for a,b in zip(Y-my,Y-my)]))
    return A / (B * C)

In [7]:
arr_coef = []
for i in range(len(dataset)):
    arr_coef.append([])
    
for i in range(len(dataset)):
    for j in range(len(dataset)):
        X = list(dataset[i,:])
        Y = list(dataset[j,:])
        x_m = np.mean(X)
        y_m = np.mean(Y)
        arr_coef[i].append(pearson_coef(X,Y,x_m,y_m))

In [49]:
'''A = list(dataset[0,:])
B = list(dataset[1,:])
print(A)
print(B)
print(A - np.mean(A))
print(B - np.mean(B))
print(sum((A - np.mean(A))*(B - np.mean(B))))

meu
[a*b for a,b in zip(meu,meu)]'''

[5.1, 3.5, 1.4, 0.2]
[4.9, 3.0, 1.4, 0.2]
[ 2.55  0.95 -1.15 -2.35]
[ 2.525  0.625 -0.975 -2.175]
13.265


In [8]:
arr_coef

[[1.0,
  0.9959986612402602,
  0.9999739110463369,
  0.9981684517756669,
  0.999347331500376,
  0.999586053147282,
  0.9988111930894704,
  0.9995381471092247,
  0.9980766422884699,
  0.9965519611817498,
  0.9999848493681356,
  0.9980873281627498,
  0.9969025266384051,
  0.9997770416664601,
  0.9975956606095019,
  0.994986568047197,
  0.9969834430294693,
  0.9998685476102342,
  0.9993924058088722,
  0.9983327018611075,
  0.9959963868284842,
  0.9993862480882908,
  0.9914083460398299,
  0.996978773097599,
  0.9913076496851791,
  0.9922124764525787,
  0.9994838709333603,
  0.9997033754910112,
  0.999375970174405,
  0.9972721559535701,
  0.9959489652513991,
  0.9969972846313159,
  0.9937383854578867,
  0.9958657788510079,
  0.9965519611817498,
  0.9984177489589913,
  0.9982856688089489,
  0.9965519611817498,
  0.9997753792621142,
  0.999389515345294,
  0.9993480935911694,
  0.9757521273387465,
  0.9990921440362365,
  0.9997834794821433,
  0.9965154426677871,
  0.9967492353971054,
  0.99766

In [46]:
dataset

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3